config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources 'rooms', only: [:index, :create] do
    resources 'messages', only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :text, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      render :index
    end
  end

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Gappa is a bootstrap minimal & clean admin template">
    <meta name="keywords" content="chat, chat platform, discussion, video call, voice call, communication, conversation, messange, messanger, talk">
    <meta name="author" content="Themesbox">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Tutti</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <!-- Fevicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">
    <!-- Start css -->
    <!-- Slick css -->
    <link href="/assets/plugins/slick/slick.css" rel="stylesheet">
    <link href="/assets/plugins/slick/slick-theme.css" rel="stylesheet">
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/flag-icon.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css">
    <!-- End css -->
</head>
    <%= yield %>

app/views/messages/_chat.html.erb
<div class="chat-detail">
                <div class="chat-head">
                    <div class="row align-items-center">
                        <div class="col-6">                                                
                            <ul class="list-unstyled mb-0">
                                <li class="media">
                                    <div class="user-status"></div>
                                    
                                    <div class="media-body">
                                    <h4><%= current_user.last_name %></h4>
                                    <p class="mb-0"><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'room-creaet btn-primary' %></p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        
                    </div>                                    
                </div>
                <div class="chat-body">
                    <img class="align-self-center mr-2" src="assets/images/authenticatiton-bg.jpg" alt="chat image">
                    <%= render partial: 'message', collection: @messages %>
                </div>
                <div class="chat-bottom">
                    <div class="chat-messagebar">
                        <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
                            <div class="input-group">
                                 <%= f.text_field :text, class: 'form-control', placeholder: 'チャットメッセージ入力...' %>    
                                <div class="input-group-append">
                                <%= f.submit class: 'room-creaet btn-primary', value: '送信'%> 
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>

app/views/messages/_message.html.erb
<div class="tab-content" id="chat-listContent">
    <div class="tab-pane fade show active" id="chat-first" role="tabpanel" aria-labelledby="chat-first-tab">
        
        <% if message.user.id == current_user.id %>
          <div class="chat-message chat-message-right">
              <div class="chat-message-text">
                  <span><%= message.text %></span>
              </div>
              <div class="chat-message-meta">
                  <span><%= l message.created_at %><i class="feather"></i></span>
                  <div class="chat-message-meta">
                    <span><%= message.user.last_name %><i class="feather"></i></span>
                  </div>
              </div>
          </div>
        <% else %>
          <div class="chat-message chat-message-left">
              <div class="chat-message-text">
                <span><%= message.text %></span>
              </div>
              <div class="chat-message-meta">
                  <span><%= l message.created_at %><i class="feather"></i></span>
                  <div class="chat-message-meta">
                    <span><%= message.user.last_name %><i class="feather"></i></span>
                  </div>
              </div>
          </div>
        <% end %>
    </div>
</div>     

app/views/messages/index.html.erb
<body class="light-layout">
    <!-- Start Chat Layout -->
    <div class="chat-layout">
        <!-- Start Chat Leftbar -->
        <div class="chat-leftbar">
            <div class="tab-content" id="pills-tab-justifiedContent">
                <!-- Start Chat Listbar -->
                <div class="tab-pane fade show active" id="pills-chat-justified" role="tabpanel" aria-labelledby="pills-chat-tab-justified">
                    <div class="chat-listbar">
                        <div class="chat-left-headbar">
                            <div class="row align-items-center">
                                <div class="col-9">
                                    <ul class="list-unstyled mb-0">
                                        <li class="media">
                                            
                                            <div class="media-body">
                                                <h5 class="mb-0 mt-2"><%= link_to 'Tutti', root_path %></h5>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>  
                                                          
                        <div class="chat-left-body">
                            <% current_user.rooms.each do |room| %>     
                                <div class="nav flex-column nav-pills chat-userlist" id="chat-list-tab" role="tablist" aria-orientation="vertical">
                                    <div class="nav-link active">
                                            <div class="media-body">
                                                <h5><%= link_to room.name, room_messages_path(room) %></h5>
                                            </div>                                      
                                    </div>
                                </div>
                            <% end %>    
                        </div>                                       
                    </div>                                    
                </div>
                <!-- End Chat Listbar -->
  
                
            </div>
            <div class="chat-menu">
                
            </div>
        </div>
        <!-- End Chat Leftbar -->
        <!-- Start Chat Rightbar -->  
        <div class="chat-rightbar">
            <!-- Start Chat Detail -->
            <%= render 'chat' %>
            <!-- End Chat Detail -->
        </div>
        <!-- End Chat Rightbar -->
    </div>
    <!-- End Chat Layout -->
    <!-- Start js -->        
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/modernizr.min.js"></script>
    <script src="/assets/js/detect.js"></script>
    <script src="/assets/js/jquery.slimscroll.js"></script>
    <script src="/assets/js/vertical-menu.js"></script>
    <!-- Slick js -->
    <script src="/assets/plugins/slick/slick.min.js"></script>
    <!-- Core js -->
    <script src="/assets/js/core.js"></script>
    <!-- End js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

</body>
</html>

app/views/rooms/index.html.erb
<body class="light-layout">
    <!-- Start Chat Layout -->
    <div class="chat-layout">
        <!-- Start Chat Leftbar -->
        <div class="chat-leftbar">
            <div class="tab-content" id="pills-tab-justifiedContent">
                <!-- Start Chat Listbar -->
                <div class="tab-pane fade show active" id="pills-chat-justified" role="tabpanel" aria-labelledby="pills-chat-tab-justified">
                    <div class="chat-listbar">
                        <div class="chat-left-headbar">
                            <div class="row align-items-center">
                                <div class="col-9">
                                    <ul class="list-unstyled mb-0">
                                        <li class="media">
                                            
                                            <div class="media-body">
                                                <h5 class="mb-0 mt-2"><%= link_to 'Tutti', root_path %></h5>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>  
                        <div class="chat-left-search">
                            <%=form_with model: @room, local: true do |f|%>
                                <%= f.text_field :name, class: 'form-control', placeholder: 'ルーム名'%>
                                <p class="chat-member-select">チャットするユーザーを選択してください</p>

                                <% if @room.errors.any? %>
                                    <div class="error-alert">
                                        <ul>
                                            <% @room.errors.full_messages.each do |message| %>
                                            <li class='error-message'><%= message %></li>
                                            <% end %>
                                        </ul>
                                    </div>
                                <% end %>                                   

                                <select name="room[user_ids][]" >
                                    <%= f.collection_check_boxes :user_ids, User.where.not(id: current_user.id).all, :id, :last_name, {include_hidden: false} %>
                                </select>
                                <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>

                                <div class="input-group-append">
                                    <%= f.submit class: 'room-creaet btn-primary', value: 'ルーム作成'%>
                                </div>    
                            <% end %>
                        </div>                                     
                        <div class="chat-left-body">
                            <% current_user.rooms.each do |room| %>     
                                <div class="nav flex-column nav-pills chat-userlist" id="chat-list-tab" role="tablist" aria-orientation="vertical">
                                    <div class="nav-link active">
                                            <div class="media-body">
                                                <h5><%= link_to room.name, room_messages_path(room) %></h5>
                                            </div>                                      
                                    </div>
                                </div>
                            <% end %>    
                        </div>                                       
                    </div>                                    
                </div>
                <!-- End Chat Listbar -->
  
                
            </div>
            <div class="chat-menu">
            </div>
        </div>
        <!-- End Chat Leftbar -->
        <!-- Start Chat Rightbar -->  
        <div class="chat-rightbar">
            <!-- Start Chat Detail -->
            <div class="chat-detail">
                <div class="chat-head">
                    <div class="row align-items-center">
                        <div class="col-6">                                                
                            <ul class="list-unstyled mb-0">
                                <li class="media">
                                    <div class="user-status"></div>
                                    
                                    <div class="media-body">
                                        <h4><%= current_user.last_name %></h4>
                                        <p class="mb-0"><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'room-creaet btn-primary' %></p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        
                    </div>                                    
                </div>
                <div class="chat-body">
                                        
                </div>
                <div class="chat-bottom">
                    <div class="chat-messagebar">
                        <form>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <a href="#" id="button-addonmic"><i class="feather"></i></a>
                                </div>  
                                <input type="text" class="form-control" placeholder="チャットメッセージ入力..." aria-label="Text">
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- End Chat Detail -->
        </div>
        <!-- End Chat Rightbar -->
    </div>
    <!-- End Chat Layout -->
    <!-- Start js -->        
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/modernizr.min.js"></script>
    <script src="/assets/js/detect.js"></script>
    <script src="/assets/js/jquery.slimscroll.js"></script>
    <script src="/assets/js/vertical-menu.js"></script>
    <!-- Slick js -->
    <script src="/assets/plugins/slick/slick.min.js"></script>
    <!-- Core js -->
    <script src="/assets/js/core.js"></script>
    <!-- End js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

</body>
</html>

app/views/rooms/show.html.erb
<body class="light-layout">
    <!-- Start Chat Layout -->
    <div class="chat-layout">
        <!-- Start Chat Leftbar -->
        <div class="chat-leftbar">
            <div class="tab-content" id="pills-tab-justifiedContent">
                <!-- Start Chat Listbar -->
                <div class="tab-pane fade show active" id="pills-chat-justified" role="tabpanel" aria-labelledby="pills-chat-tab-justified">
                    <div class="chat-listbar">
                        <div class="chat-left-headbar">
                            <div class="row align-items-center">
                                <div class="col-9">
                                    <ul class="list-unstyled mb-0">
                                        <li class="media">
                                            <img class="align-self-center mr-2" src="assets/images/logo.svg" alt="Generic placeholder image">
                                            <div class="media-body">
                                                <h5 class="mb-0 mt-2">Tutti</h5>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>  
                                                          
                        <div class="chat-left-body">
                            <% current_user.rooms.each do |room| %>     
                                <div class="nav flex-column nav-pills chat-userlist" id="chat-list-tab" role="tablist" aria-orientation="vertical">
                                    <div class="nav-link active">
                                            <div class="media-body">
                                                <h5><%= link_to room.name, room_path(room) %></h5>
                                            </div>                                      
                                    </div>
                                </div>
                            <% end %>    
                        </div>                                       
                    </div>                                    
                </div>
                <!-- End Chat Listbar -->
  
                
            </div>
            <div class="chat-menu">
                
            </div>
        </div>
        <!-- End Chat Leftbar -->
        <!-- Start Chat Rightbar -->  
        <div class="chat-rightbar">
            <!-- Start Chat Detail -->
            <div class="chat-detail">
                <div class="chat-head">
                    <div class="row align-items-center">
                        <div class="col-6">                                                
                            <ul class="list-unstyled mb-0">
                                <li class="media">
                                    <div class="user-status"></div>
                                    <img class="align-self-center rounded-circle" src="assets/images/girl.svg" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <h5><%= current_user.last_name %></h5>
                                        <p class="mb-0"><%= button_to 'Exit', destroy_user_session_path, method: :delete %></p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        
                    </div>                                    
                </div>
                <div class="chat-body">
                    <img class="align-self-center mr-2" src="assets/images/authenticatiton-bg.jpg" alt="chat image">                    
                </div>
                <div class="chat-bottom">
                    <div class="chat-messagebar">
                        <form>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <a href="#" id="button-addonmic"><i class="feather icon-mic"></i></a>
                                </div>  
                                <input type="text" class="form-control" placeholder="チャットメッセージ入力..." aria-label="Text">
                                <div class="input-group-append">
                                    <a href="#" class="mr-3" id="button-addonlink"><i class="feather icon-paperclip"></i></a>
                                    <a href="#" id="button-addonsend"><i class="feather icon-send"></i></a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- End Chat Detail -->
        </div>
        <!-- End Chat Rightbar -->
    </div>
    <!-- End Chat Layout -->
    <!-- Start js -->        
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/modernizr.min.js"></script>
    <script src="/assets/js/detect.js"></script>
    <script src="/assets/js/jquery.slimscroll.js"></script>
    <script src="/assets/js/vertical-menu.js"></script>
    <!-- Slick js -->
    <script src="/assets/plugins/slick/slick.min.js"></script>
    <!-- Core js -->
    <script src="/assets/js/core.js"></script>
    <!-- End js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>